from . import insurance_category
from . import insurance_term
from . import insurance_agent
from . import insurance_nominee
from . import insurance_document
from . import insurance_claim
from . import insurance_policy
from . import res_partner
from . import account_move
